version: "3.9"

networks:
  universityCRM-dev:
    driver: bridge

services:
  universityCRM:
    image: crm:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6500:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=dockerdatabase;username=postgres; password=12345"
    networks:
      - universityCRM-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - ./databasefordocker:/var/lib/postgresql/data     
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "dockerdatabase"
    networks:
      - universityCRM-dev

    
      