//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionText {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionText() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("University.DataBase.Resources.ExceptionText", typeof(ExceptionText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InvalidHomeworkName {
            get {
                return ResourceManager.GetString("InvalidHomeworkName", resourceCulture);
            }
        }
        
        internal static string HomeworkExist {
            get {
                return ResourceManager.GetString("HomeworkExist", resourceCulture);
            }
        }
        
        internal static string InvalidLection {
            get {
                return ResourceManager.GetString("InvalidLection", resourceCulture);
            }
        }
        
        internal static string InvalidHomework {
            get {
                return ResourceManager.GetString("InvalidHomework", resourceCulture);
            }
        }
        
        internal static string InvalidLectionName {
            get {
                return ResourceManager.GetString("InvalidLectionName", resourceCulture);
            }
        }
        
        internal static string InvalidLectorName {
            get {
                return ResourceManager.GetString("InvalidLectorName", resourceCulture);
            }
        }
        
        internal static string InvalidStudentName {
            get {
                return ResourceManager.GetString("InvalidStudentName", resourceCulture);
            }
        }
        
        internal static string InvalidUniversityName {
            get {
                return ResourceManager.GetString("InvalidUniversityName", resourceCulture);
            }
        }
        
        internal static string InvalidLector {
            get {
                return ResourceManager.GetString("InvalidLector", resourceCulture);
            }
        }
        
        internal static string InvalidStudent {
            get {
                return ResourceManager.GetString("InvalidStudent", resourceCulture);
            }
        }
        
        internal static string InvalidUniversity {
            get {
                return ResourceManager.GetString("InvalidUniversity", resourceCulture);
            }
        }
        
        internal static string LectionExist {
            get {
                return ResourceManager.GetString("LectionExist", resourceCulture);
            }
        }
        
        internal static string LectorExist {
            get {
                return ResourceManager.GetString("LectorExist", resourceCulture);
            }
        }
        
        internal static string StudentExist {
            get {
                return ResourceManager.GetString("StudentExist", resourceCulture);
            }
        }
        
        internal static string UniversityExist {
            get {
                return ResourceManager.GetString("UniversityExist", resourceCulture);
            }
        }
        
        internal static string EmptyUniversity {
            get {
                return ResourceManager.GetString("EmptyUniversity", resourceCulture);
            }
        }
        
        internal static string EmptyHomework {
            get {
                return ResourceManager.GetString("EmptyHomework", resourceCulture);
            }
        }
        
        internal static string EmptyLection {
            get {
                return ResourceManager.GetString("EmptyLection", resourceCulture);
            }
        }
        
        internal static string EmptyLector {
            get {
                return ResourceManager.GetString("EmptyLector", resourceCulture);
            }
        }
        
        internal static string EmptyStudent {
            get {
                return ResourceManager.GetString("EmptyStudent", resourceCulture);
            }
        }
        
        internal static string EmptyMarkAndVisited {
            get {
                return ResourceManager.GetString("EmptyMarkAndVisited", resourceCulture);
            }
        }
        
        internal static string InvalidMarkAndVisited {
            get {
                return ResourceManager.GetString("InvalidMarkAndVisited", resourceCulture);
            }
        }
    }
}
