//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResLoggingText {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLoggingText() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("University.BusinessLogic.Resources.ResLoggingText", typeof(ResLoggingText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddedHomework {
            get {
                return ResourceManager.GetString("AddedHomework", resourceCulture);
            }
        }
        
        internal static string ReadedHomework {
            get {
                return ResourceManager.GetString("ReadedHomework", resourceCulture);
            }
        }
        
        internal static string UpdatedHomework {
            get {
                return ResourceManager.GetString("UpdatedHomework", resourceCulture);
            }
        }
        
        internal static string DeletedHomework {
            get {
                return ResourceManager.GetString("DeletedHomework", resourceCulture);
            }
        }
        
        internal static string AddedUniversity {
            get {
                return ResourceManager.GetString("AddedUniversity", resourceCulture);
            }
        }
        
        internal static string AddedLector {
            get {
                return ResourceManager.GetString("AddedLector", resourceCulture);
            }
        }
        
        internal static string AddedLection {
            get {
                return ResourceManager.GetString("AddedLection", resourceCulture);
            }
        }
        
        internal static string AddedStudent {
            get {
                return ResourceManager.GetString("AddedStudent", resourceCulture);
            }
        }
        
        internal static string DeletedUniversity {
            get {
                return ResourceManager.GetString("DeletedUniversity", resourceCulture);
            }
        }
        
        internal static string DeletedStudent {
            get {
                return ResourceManager.GetString("DeletedStudent", resourceCulture);
            }
        }
        
        internal static string DeletedLector {
            get {
                return ResourceManager.GetString("DeletedLector", resourceCulture);
            }
        }
        
        internal static string DeletedLection {
            get {
                return ResourceManager.GetString("DeletedLection", resourceCulture);
            }
        }
        
        internal static string ReadedLection {
            get {
                return ResourceManager.GetString("ReadedLection", resourceCulture);
            }
        }
        
        internal static string ReadedUniversity {
            get {
                return ResourceManager.GetString("ReadedUniversity", resourceCulture);
            }
        }
        
        internal static string ReadedLector {
            get {
                return ResourceManager.GetString("ReadedLector", resourceCulture);
            }
        }
        
        internal static string ReadedStudent {
            get {
                return ResourceManager.GetString("ReadedStudent", resourceCulture);
            }
        }
        
        internal static string UpdatedUniversity {
            get {
                return ResourceManager.GetString("UpdatedUniversity", resourceCulture);
            }
        }
        
        internal static string UpdatedStudent {
            get {
                return ResourceManager.GetString("UpdatedStudent", resourceCulture);
            }
        }
        
        internal static string UpdatedLection {
            get {
                return ResourceManager.GetString("UpdatedLection", resourceCulture);
            }
        }
        
        internal static string UpdatedLector {
            get {
                return ResourceManager.GetString("UpdatedLector", resourceCulture);
            }
        }
    }
}
